"""Local backup file store.

A netconf-mcp backup is a single ``.tar.gz`` containing the per-section
XML files produced by ``netconf_backup`` (one ``<section>.xml`` per direct
child of ``<drivenets-top>``: ``interfaces.xml``, ``protocols.xml``,
``system.xml``, ...). The tarball lives on the **local machine** under
:data:`BACKUP_DIR` (``<state_dir>/backups/nc``, honouring
``$QACTL_STATE_DIR``). ``qactl`` builds and restores backups on the host
it runs on; the shared ``dnftp`` artefact host is reserved for the large
device-pushed tech-support tarballs. Restore replays the section XML back
over the live NETCONF session, so no on-device file transfer is involved.

Buckets
-------

Every backup either lives in :data:`BACKUP_DIR` directly (the "root"
bucket, ``bucket=None``) or under a one-level subdirectory
``<BACKUP_DIR>/<bucket>/`` named by the agent (e.g. ``bug-1234-repro``,
``save-for-later``). Buckets are a pure directory-level concept — the
filename grammar is unchanged, so the same backup name can coexist in
multiple buckets without colliding. Bucket names are sanitised to
``[A-Za-z0-9._-]{1,60}``, may not contain ``__`` (reserved as the
filename separator), may not contain ``/`` (one level only), and must
not match the canonical filename shape (so a bucket can't be confused
for a backup file).

Filename convention::

    <device>__<YYYYMMDD-HHMMSS>[__<desc>].tar.gz

- ``device`` is the alias (``cl``, ``sa``, ...), pinned by the tool — not
  user-supplied. This guarantees that a restore can only target the device
  the file was captured from.
- ``YYYYMMDD-HHMMSS`` is UTC, generated by the MCP at backup time.
- ``description`` is optional, sanitised to ``[A-Za-z0-9._-]{1,40}``.
  Missing description drops the trailing ``__<description>`` segment
  entirely.
- ``.tar.gz`` is a real tarball: ``netconf_backup`` writes the section
  files under ``<basename>/`` inside the archive so unpacking yields a
  directory layout ``netconf_restore`` / ``netconf_diff`` can hand
  straight to :func:`xml_payload.load_restore_sections`.

This file is intentionally self-contained — it does not import anything
from sibling MCP packages (cli-mcp, etc.). Constants and helpers are
duplicated rather than shared so the two MCPs can be deployed and
versioned independently.
"""

from __future__ import annotations

import io
import os
import posixpath
import re
import shutil
import tarfile
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import List, Optional, Tuple

from qactl.dnos.core.paths import state_dir

# netconf-mcp backups used to live on the shared ``dnftp`` SFTP host; a
# standalone qactl keeps them on the local machine instead (dnftp is now
# reserved for device-pushed tech-support tarballs). ``BACKUP_HOST`` is a
# display sentinel kept so the list-envelope shape is unchanged.
BACKUP_HOST = "local"


# --------------------------------------------------------------------------
# Local backup root. Honours $QACTL_STATE_DIR via qactl.core.paths. The
# path helpers below call _root() dynamically; ``BACKUP_DIR`` is a
# convenience snapshot used by the list envelope for display.
# --------------------------------------------------------------------------


def _root() -> str:
    """Local backup root: ``<state_dir>/backups/nc``."""
    return str(state_dir("backups") / "nc")


BACKUP_DIR = _root()

# Verification floor. A non-empty gzip-compressed tarball with even one
# tiny XML section comfortably exceeds this; sub-128 byte files are
# essentially always truncated/empty writes.
MIN_BYTES = 128


# --------------------------------------------------------------------------
# Filename grammar
# --------------------------------------------------------------------------

_TAR_SUFFIX = ".tar.gz"

_FILENAME_RE = re.compile(
    r"^(?P<device>[A-Za-z0-9][A-Za-z0-9._-]*?)"
    r"__(?P<ts>\d{8}-\d{6})"
    r"(?:__(?P<description>[A-Za-z0-9][A-Za-z0-9._-]*))?"
    r"\.tar\.gz$"
)

_DESCRIPTION_CLEAN_RE = re.compile(r"[^A-Za-z0-9._-]+")
_DESCRIPTION_MAX = 40
_DEVICE_MAX = 40

_BUCKET_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,59}$")
_BUCKET_MAX = 60


@dataclass(frozen=True)
class BackupFile:
    """Parsed view of one backup on the local disk.

    ``path`` is the absolute local path of the tarball under the backup
    root. ``bucket`` is ``None`` for files in :data:`BACKUP_DIR` directly,
    or the sub-directory name for files in a sub-bucket. ``basename`` is the
    filename minus the ``.tar.gz`` suffix and is the directory name used
    inside the archive.
    """

    filename: str
    device: str
    timestamp_utc: str              # "YYYY-MM-DDTHH:MM:SSZ"
    description: Optional[str]
    bucket: Optional[str]
    size_bytes: int
    path: str

    @property
    def basename(self) -> str:
        return self.filename[: -len(_TAR_SUFFIX)]


def _utc_timestamp() -> str:
    """``YYYYMMDD-HHMMSS`` in UTC, used in backup filenames."""
    return datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")


def default_bucket() -> str:
    """Today's UTC date as ``YYYY-MM-DD`` — the implicit bucket for ``netconf_backup``.

    When the agent does not pass an explicit ``bucket=``, the backup tool
    lands the tarball in this date-named sub-directory so backups are
    auto-grouped by capture day instead of piling up in the root. The
    string is a legal bucket name (alnum + ``-``, no ``__``, doesn't
    collide with the canonical filename shape) so it round-trips through
    :func:`validate_bucket` and :func:`ensure_dir` unchanged.
    """
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _sanitise_description(description: Optional[str]) -> Optional[str]:
    """Reduce description to the allowed charset, truncate, drop if empty."""
    if description is None:
        return None
    cleaned = _DESCRIPTION_CLEAN_RE.sub("_", description.strip()).strip("._-")
    if not cleaned:
        return None
    return cleaned[:_DESCRIPTION_MAX]


def validate_device(device: str) -> Optional[str]:
    """Return an error string if ``device`` is not a legal filename segment."""
    if not isinstance(device, str) or not device:
        return "device must be a non-empty string."
    if len(device) > _DEVICE_MAX:
        return f"device name too long (> {_DEVICE_MAX} chars)."
    if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._-]*$", device):
        return (
            "device name must start with alnum and contain only "
            "[A-Za-z0-9._-]."
        )
    if "__" in device:
        return "device name must not contain '__' (reserved as field separator)."
    return None


def validate_bucket(bucket: Optional[str]) -> Optional[str]:
    """Return an error string if ``bucket`` is not a legal sub-directory name."""
    if bucket is None:
        return None
    if not isinstance(bucket, str) or not bucket:
        return "bucket must be a non-empty string (or None / omitted)."
    if len(bucket) > _BUCKET_MAX:
        return f"bucket too long (> {_BUCKET_MAX} chars)."
    if "/" in bucket:
        return "bucket must not contain '/' (one level of nesting only)."
    if "__" in bucket:
        return "bucket must not contain '__' (reserved as field separator)."
    if not _BUCKET_RE.match(bucket):
        return (
            "bucket must start with alnum and contain only "
            "[A-Za-z0-9._-]."
        )
    if parse_filename(bucket) is not None:
        return (
            "bucket must not match the canonical backup filename shape "
            "(would be ambiguous with a file in the root bucket)."
        )
    return None


def make_filename(device: str, description: Optional[str] = None) -> str:
    """Build a canonical ``.tar.gz`` backup filename for ``device``."""
    err = validate_device(device)
    if err:
        raise ValueError(err)
    ts = _utc_timestamp()
    clean_description = _sanitise_description(description)
    if clean_description:
        return f"{device}__{ts}__{clean_description}{_TAR_SUFFIX}"
    return f"{device}__{ts}{_TAR_SUFFIX}"


def parse_filename(filename: str) -> Optional[BackupFile]:
    """Parse a bare filename into :class:`BackupFile` without touching the network."""
    m = _FILENAME_RE.match(filename)
    if not m:
        return None
    ts_raw = m.group("ts")  # YYYYMMDD-HHMMSS
    iso = (
        f"{ts_raw[0:4]}-{ts_raw[4:6]}-{ts_raw[6:8]}T"
        f"{ts_raw[9:11]}:{ts_raw[11:13]}:{ts_raw[13:15]}Z"
    )
    return BackupFile(
        filename=filename,
        device=m.group("device"),
        timestamp_utc=iso,
        description=m.group("description"),
        bucket=None,
        size_bytes=0,
        path=posixpath.join(_root(), filename),
    )


def _bucket_dir(bucket: Optional[str]) -> str:
    """Absolute path of the local backup directory for ``bucket``."""
    if bucket is None:
        return _root()
    return posixpath.join(_root(), bucket)


def _file_path(filename: str, bucket: Optional[str]) -> str:
    """Absolute path of a backup file on the local disk."""
    return posixpath.join(_bucket_dir(bucket), filename)


# --------------------------------------------------------------------------
# Local-filesystem helpers
# --------------------------------------------------------------------------


def _build_backupfile(
    filename: str, size_bytes: int, bucket: Optional[str]
) -> Optional[BackupFile]:
    parsed = parse_filename(filename)
    if parsed is None:
        return None
    return BackupFile(
        filename=parsed.filename,
        device=parsed.device,
        timestamp_utc=parsed.timestamp_utc,
        description=parsed.description,
        bucket=bucket,
        size_bytes=size_bytes,
        path=_file_path(filename, bucket),
    )


def stat_backup(
    filename: str, bucket: Optional[str] = None
) -> Optional[BackupFile]:
    """Parse + local-stat. Returns ``None`` if the name is malformed or the
    file does not exist in the given bucket."""
    if parse_filename(filename) is None:
        return None
    if validate_bucket(bucket) is not None:
        return None
    try:
        size = os.stat(_file_path(filename, bucket)).st_size
    except OSError:
        return None
    return _build_backupfile(filename, int(size), bucket)


def _subdirs(path: str) -> List[str]:
    try:
        return [e.name for e in os.scandir(path) if e.is_dir()]
    except OSError:
        return []


def _list_one(
    bucket: Optional[str],
    device: Optional[str],
) -> List[BackupFile]:
    """List backups inside one bucket (root if ``bucket`` is None)."""
    out: List[BackupFile] = []
    try:
        entries = list(os.scandir(_bucket_dir(bucket)))
    except OSError:
        return out
    for entry in entries:
        if not entry.is_file():
            continue
        backup = _build_backupfile(entry.name, int(entry.stat().st_size), bucket)
        if backup is None:
            continue
        if device is not None and backup.device != device:
            continue
        out.append(backup)
    return out


def list_backups(
    device: Optional[str] = None,
    limit: Optional[int] = 100,
    bucket: Optional[str] = None,
) -> List[BackupFile]:
    """List backups under the local backup root, newest first.

    ``bucket`` semantics:

    - ``None`` (default): list every backup across the root bucket AND every
      sub-bucket. Each entry's ``bucket`` field tells you which bucket the
      file lives in (``None`` for root).
    - ``"<name>"``: list only that bucket's contents.
    """
    if bucket is not None and validate_bucket(bucket) is not None:
        return []
    out: List[BackupFile] = []
    if bucket is not None:
        out.extend(_list_one(bucket, device))
    else:
        out.extend(_list_one(None, device))
        for name in _subdirs(_root()):
            if validate_bucket(name) is not None:
                continue
            out.extend(_list_one(name, device))
    out.sort(key=lambda b: (b.filename, b.bucket or ""), reverse=True)
    if limit is not None and limit > 0:
        out = out[:limit]
    return out


def list_buckets() -> List[str]:
    """Return the sub-bucket directory names under the backup root, sorted."""
    out = [n for n in _subdirs(_root()) if validate_bucket(n) is None]
    out.sort()
    return out


def list_orphans() -> List[str]:
    """Names under the backup root (and any sub-bucket) that don't match the
    canonical shape."""
    out: List[str] = []
    root = _root()
    try:
        root_entries = list(os.scandir(root))
    except OSError:
        return out
    sub_buckets: List[str] = []
    for entry in root_entries:
        if entry.is_dir():
            if validate_bucket(entry.name) is None:
                sub_buckets.append(entry.name)
            else:
                out.append(entry.name + "/")
            continue
        if not entry.is_file():
            continue
        if parse_filename(entry.name) is None:
            out.append(entry.name)
    for bucket in sub_buckets:
        try:
            entries = list(os.scandir(posixpath.join(root, bucket)))
        except OSError:
            continue
        for entry in entries:
            if not entry.is_file():
                continue
            if parse_filename(entry.name) is None:
                out.append(f"{bucket}/{entry.name}")
    out.sort()
    return out


def ensure_dir(bucket: Optional[str] = None) -> None:
    """Make sure the backup root (and ``<root>/<bucket>`` if given) exists. Idempotent."""
    if bucket is not None:
        err = validate_bucket(bucket)
        if err:
            raise ValueError(err)
    os.makedirs(_bucket_dir(bucket), exist_ok=True)


def delete_backup(filename: str, bucket: Optional[str] = None) -> bool:
    """Delete a local backup. Returns True if deleted, False if missing.

    Refuses to touch anything whose name doesn't parse — a thin safety net
    against a caller smuggling a path traversal through the ``filename`` arg.
    """
    if parse_filename(filename) is None:
        raise ValueError(
            f"refusing to delete {filename!r}: not a canonical backup name."
        )
    err = validate_bucket(bucket)
    if err:
        raise ValueError(f"refusing to delete with invalid bucket: {err}")
    try:
        os.remove(_file_path(filename, bucket))
        return True
    except FileNotFoundError:
        return False
    except OSError:
        return False


# --------------------------------------------------------------------------
# Tarball pack / upload / download
# --------------------------------------------------------------------------


def pack_sections(
    sections: List[Tuple[str, str]],
    *,
    arc_root: str,
) -> bytes:
    """Build an in-memory ``.tar.gz`` of section XML files.

    ``sections`` is a list of ``(section_name, xml_text)`` pairs (the same
    shape returned by :func:`xml_payload.extract_dn_top_payloads`, or
    derived from a directory of split files). Each entry is written as
    ``<arc_root>/<section_name>.xml`` inside the archive — the
    ``arc_root`` matches the basename of the destination filename so
    extraction yields a self-describing directory.

    Returns the raw gzip-compressed tarball bytes; the caller is
    responsible for uploading them via :func:`upload_bytes` (or writing
    them to disk if testing).
    """
    if not sections:
        raise ValueError("pack_sections: at least one section required")
    if not arc_root or "/" in arc_root or arc_root in (".", ".."):
        raise ValueError(f"pack_sections: invalid arc_root {arc_root!r}")

    buf = io.BytesIO()
    now = int(datetime.now(timezone.utc).timestamp())
    with tarfile.open(fileobj=buf, mode="w:gz") as tar:
        for name, xml_text in sections:
            if "/" in name or name in (".", ".."):
                raise ValueError(
                    f"pack_sections: invalid section name {name!r}"
                )
            data = xml_text.encode("utf-8")
            info = tarfile.TarInfo(name=f"{arc_root}/{name}.xml")
            info.size = len(data)
            info.mtime = now
            info.mode = 0o644
            tar.addfile(info, io.BytesIO(data))
    return buf.getvalue()


def upload_bytes(
    payload: bytes,
    filename: str,
    bucket: Optional[str] = None,
) -> BackupFile:
    """Write ``payload`` to ``<root>/[<bucket>/]<filename>`` on the local disk.

    Creates parent dirs first, writes to a ``<filename>.tmp`` and renames
    atomically into place so a half-written file never shadows an existing
    good copy. Returns the resulting :class:`BackupFile` (re-stat'd) on
    success; raises on any failure (missing/short file after write, etc.).
    The name ``upload_bytes`` is kept for call-site compatibility.
    """
    if parse_filename(filename) is None:
        raise ValueError(
            f"refusing to write {filename!r}: not a canonical backup name."
        )
    err = validate_bucket(bucket)
    if err:
        raise ValueError(f"refusing to write with invalid bucket: {err}")

    os.makedirs(_bucket_dir(bucket), exist_ok=True)
    final_path = _file_path(filename, bucket)
    tmp_path = final_path + ".tmp"
    with open(tmp_path, "wb") as fh:
        fh.write(payload)
    os.replace(tmp_path, final_path)

    size = int(os.stat(final_path).st_size)
    if size < MIN_BYTES:
        raise IOError(
            f"backup {final_path!r} is suspiciously small "
            f"({size} bytes); treating as a failed write."
        )
    backup = _build_backupfile(filename, size, bucket)
    if backup is None:
        raise RuntimeError(
            f"internal: stat'd {final_path!r} but could not parse name."
        )
    return backup


def download_to_path(
    filename: str,
    dest_path: str,
    bucket: Optional[str] = None,
) -> BackupFile:
    """Copy ``filename`` from the local backup store into ``dest_path``.

    The caller manages ``dest_path``'s lifecycle (typically a
    :class:`tempfile.TemporaryDirectory` for restore/diff). Returns the
    :class:`BackupFile` for the source on success; raises if the file is
    missing or short. The name ``download_to_path`` is kept for call-site
    compatibility.
    """
    if parse_filename(filename) is None:
        raise ValueError(
            f"refusing to read {filename!r}: not a canonical backup name."
        )
    err = validate_bucket(bucket)
    if err:
        raise ValueError(f"refusing to read with invalid bucket: {err}")

    src_path = _file_path(filename, bucket)
    parent = os.path.dirname(dest_path)
    if parent:
        os.makedirs(parent, exist_ok=True)

    try:
        size = int(os.stat(src_path).st_size)
    except FileNotFoundError:
        raise IOError(f"backup {src_path!r} not found.")
    if size < MIN_BYTES:
        raise IOError(
            f"backup {src_path!r} is suspiciously small "
            f"({size} bytes); refusing to read."
        )
    shutil.copyfile(src_path, dest_path)

    backup = _build_backupfile(filename, size, bucket)
    if backup is None:
        raise RuntimeError(
            f"internal: parsed {filename!r} for stat but not for build."
        )
    return backup


# Reasonable upper bound on a single section payload. Full DNOS configs
# are typically <1 MB compressed; an XML section that exceeds this is
# almost certainly a tampered or corrupt archive. Bumping this requires
# evidence from a real device.
_EXTRACT_SECTION_MAX_BYTES = 64 * 1024 * 1024


def extract_to_dir(
    tar_path: str,
    dest_dir: str,
    *,
    expected_arc_root: str,
) -> List[str]:
    """Safely extract a netconf-mcp backup tarball into ``dest_dir``.

    Validates each member is a regular file under
    ``<expected_arc_root>/<name>.xml`` (no absolute paths, no ``..``,
    no symlinks, no nested dirs). Flattens the archive: the
    ``expected_arc_root`` prefix is stripped on extraction so the
    resulting layout is ``dest_dir/<section>.xml``, which
    :func:`xml_payload.load_restore_sections` can consume directly.

    Returns the list of absolute paths written to ``dest_dir``.
    """
    if not expected_arc_root or "/" in expected_arc_root:
        raise ValueError(
            f"extract_to_dir: invalid expected_arc_root {expected_arc_root!r}"
        )

    os.makedirs(dest_dir, exist_ok=True)
    written: List[str] = []
    seen_names: set[str] = set()

    with tarfile.open(tar_path, "r:gz") as tar:
        for info in tar.getmembers():
            if not info.isreg():
                raise ValueError(
                    f"extract_to_dir: rejecting non-regular member "
                    f"{info.name!r} (type {info.type!r})"
                )
            name = info.name
            if name.startswith("/") or ".." in name.split("/"):
                raise ValueError(
                    f"extract_to_dir: rejecting unsafe path {name!r}"
                )
            prefix = expected_arc_root + "/"
            if not name.startswith(prefix):
                raise ValueError(
                    f"extract_to_dir: member {name!r} not under "
                    f"expected root {expected_arc_root!r}"
                )
            tail = name[len(prefix):]
            if "/" in tail or not tail.endswith(".xml"):
                raise ValueError(
                    f"extract_to_dir: member {name!r} must be a flat "
                    "<section>.xml under the archive root"
                )
            if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._-]*\.xml$", tail):
                raise ValueError(
                    f"extract_to_dir: section filename {tail!r} fails "
                    "[A-Za-z0-9._-]+.xml shape check"
                )
            if tail in seen_names:
                raise ValueError(
                    f"extract_to_dir: duplicate section file {tail!r}"
                )
            if int(info.size or 0) > _EXTRACT_SECTION_MAX_BYTES:
                raise ValueError(
                    f"extract_to_dir: member {name!r} too large "
                    f"({info.size} bytes; cap "
                    f"{_EXTRACT_SECTION_MAX_BYTES})"
                )
            seen_names.add(tail)

            src = tar.extractfile(info)
            if src is None:
                raise ValueError(
                    f"extract_to_dir: could not open member {name!r}"
                )
            data = src.read()
            dest_path = os.path.join(dest_dir, tail)
            with open(dest_path, "wb") as fh:
                fh.write(data)
            written.append(dest_path)

    written.sort()
    return written


__all__ = [
    "BACKUP_HOST",
    "BACKUP_DIR",
    "MIN_BYTES",
    "BackupFile",
    "validate_device",
    "validate_bucket",
    "default_bucket",
    "make_filename",
    "parse_filename",
    "stat_backup",
    "list_backups",
    "list_buckets",
    "list_orphans",
    "ensure_dir",
    "delete_backup",
    "pack_sections",
    "upload_bytes",
    "download_to_path",
    "extract_to_dir",
]
