"""Core-dump surface (issue #65): list core bundles + extract a backtrace.

Two sibling tools wrapping the manual crash-triage recipe proven live on
OHADZS-NCP1 (bgpd SIGABRT, 2026-07-02):

- ``list_cores`` — wrap the DNOS CLI ``show file core list`` into a parsed
  table (type / id / file_name / size / last_modified).
- ``get_core_backtrace`` — given the full name printed by ``list_cores``
  (e.g. ``routing_engine/core-bgpd.cpid-199103.sig-6....tar``), extract the
  tar into a scratch workdir on the device, decompress the ``.lz4`` core,
  run gdb (``-batch -ex bt``) against the crashed binary, grep the bundled
  stderr log for the assert line, and clean the workdir up.

v1 scope (per the issue's scope-down comment): core bundles are NOT uniform
across processes/containers, so backtrace extraction supports
**routing_engine cores only** (bgpd and friends). Other containers error
out with the manual-recipe pointer instead of guessing.

Live-run gotchas baked in:

- gdb's debuginfod host is NOT reachable from the device — always disabled
  via ``-iex 'set debuginfod enabled off'`` to avoid the interactive prompt.
- The crashed binary path comes from the bundle's ``process.info.<cpid>``
  (``fullpath=`` line) — never derived from the tar name, because a core
  may be named after a *thread* (``core-QuaggaLogger...`` is still bgpd).
"""

from __future__ import annotations

import re
from typing import Any, Dict, List, Optional, Tuple

from dnctl.cli.core.envelope import error_response, make_response
from dnctl.cli.core.errors import (
    CORE_BT_NEXT_ACTION,
    CORE_BT_UNSUPPORTED_NEXT_ACTION,
    CORE_LIST_NEXT_ACTION,
)
from dnctl.cli.core.runner import _run_on_device
from dnctl.cli.core.session import DEFAULT_CMD_TIMEOUT, DEFAULT_PASSWORD, DEFAULT_USER
from dnctl.cli.core.shell_exec import run_linux_on_device
from dnctl.cli.vendors import CAP_SHELL, CAP_SHOW, requires


SHOW_FILE_CORE_LIST = "show file core list"

_CORE_DUMPS_DIR = "/core/core_dumps/containers"

# v1: only routing_engine bundles have a proven, uniform layout
# (<container>/<core>.lz4 + process.info.<cpid> + logs/*.stderr.log.gz).
_SUPPORTED_CONTAINERS = frozenset({"routing_engine"})

# Floor for the decompress+gdb step: a ~400 MB core took ~30 s end-to-end
# on the live run, so the plain 30 s command timeout is too tight.
_BT_MIN_TIMEOUT = 180

# ``<container>/<file>.tar`` as printed by `show file core list`. The
# character classes double as shell-safety validation: both parts are
# interpolated into command lines, so nothing outside [A-Za-z0-9._-] (plus
# the one separating slash) is ever accepted.
_FULL_NAME_RE = re.compile(
    r"^(?P<container>[A-Za-z0-9_\-]+)/(?P<file>core-[A-Za-z0-9._\-]+\.tar)$"
)
_PROCESS_RE = re.compile(r"^core-(?P<proc>[^.]+)\.")
# process.info encodes the crashed binary as ``fullpath=!usr!sbin!bgpd``.
_FULLPATH_RE = re.compile(r"^fullpath=(?P<path>\S+)", re.MULTILINE)
_SIGNAL_RE = re.compile(r"Program terminated with signal (\w+)")
_GENERATED_BY_RE = re.compile(r"Core was generated by `([^']*)'")


# --- `show file core list` parsing ------------------------------------------


def _header_index(headers: List[str], label: str) -> Optional[int]:
    """Index of the first header cell that starts with ``label``, or None."""
    for idx, head in enumerate(headers):
        if head.startswith(label):
            return idx
    return None


def _parse_core_list(text: str) -> List[Dict[str, str]]:
    """Parse the ``show file core list`` pipe table into row dicts.

    Columns are located from the header row (Type / Id / File name /
    Size [Bytes] / Last modified) so reordered or added columns across
    DNOS versions don't break the parse. DNOS wraps an over-long file
    name onto a continuation row (every other cell empty) — those are
    merged back into the previous row. Each row also derives
    ``container`` and ``process`` from the file name when it looks like
    a ``<container>/core-....tar`` bundle; note ``process`` is the
    *dumping thread's* name, not necessarily the binary.
    """
    col_map = {
        "type": "type",
        "id": "id",
        "file name": "file_name",
        "size": "size",
        "last modified": "last_modified",
    }
    headers: Optional[List[str]] = None
    rows: List[Dict[str, str]] = []
    for line in (text or "").splitlines():
        if "|" not in line:
            continue
        cells = [c.strip() for c in line.split("|")]
        if all(set(c) <= {"-", "+", ""} for c in cells):
            continue
        lowered = [c.lower() for c in cells]
        if headers is None:
            if _header_index(lowered, "file name") is not None:
                headers = lowered
            continue
        record: Dict[str, str] = {}
        for label, key in col_map.items():
            idx = _header_index(headers, label)
            if idx is not None and idx < len(cells) and cells[idx]:
                record[key] = cells[idx]
        name = record.get("file_name")
        if not name:
            continue
        # A wrapped file name continues on a row with every other cell
        # empty — glue the fragment onto the previous row.
        if rows and set(record) == {"file_name"}:
            rows[-1]["file_name"] += name
            continue
        rows.append(record)
    for record in rows:
        m = _FULL_NAME_RE.match(record["file_name"])
        if m:
            record["container"] = m.group("container")
            pm = _PROCESS_RE.match(m.group("file"))
            if pm:
                record["process"] = pm.group("proc")
    return rows


@requires(CAP_SHOW)
def list_cores(
    device: Optional[str] = None,
    host: Optional[str] = None,
    user: str = DEFAULT_USER,
    password: str = DEFAULT_PASSWORD,
    timeout: int = DEFAULT_CMD_TIMEOUT,
) -> Dict[str, Any]:
    """List core-dump bundles on the device (``show file core list``).

    Runs the DNOS CLI ``show file core list`` and parses the table into
    ``cores`` — one entry per bundle with ``type`` (NCC/NCP), ``id``,
    ``file_name`` (the full ``<container>/<core>.tar`` name to feed to
    ``get_core_backtrace``), ``size``, ``last_modified``, plus derived
    ``container`` and ``process``. NOTE: ``process`` is taken from the
    core file name, which carries the *dumping thread's* name — e.g.
    ``core-QuaggaLogger...`` is still a bgpd core. The authoritative
    binary is resolved by ``get_core_backtrace`` from the bundle itself.

    Args:
        device: Device alias (cl, sa, kira, slava-1, slava-2, ariel-cl).
        host: Raw hostname/IP (alternative to device).
        user: SSH username (default dnroot).
        password: SSH password (default dnroot).
        timeout: Per-command timeout seconds.

    Response adds:
        - ``cores``: parsed rows (may be empty — no cores is a healthy box).
        - ``count``: number of rows.
    """
    response = _run_on_device(
        "list_cores", device, host, user, password,
        SHOW_FILE_CORE_LIST, timeout, CORE_LIST_NEXT_ACTION,
    )
    if response.get("status") == "ok":
        cores = _parse_core_list(response.get("stdout") or "")
        response["cores"] = cores
        response["count"] = len(cores)
    return response


# --- backtrace extraction ----------------------------------------------------


def _bt_commands(
    container: str, fname: str, binary: str, all_threads: bool,
) -> Tuple[str, str, str, str, str]:
    """Build the four shell command lines of the backtrace recipe.

    Returns ``(workdir, extract_cmd, gdb_cmd, assert_cmd, cleanup_cmd)``.
    ``binary`` may be a placeholder in dry-run mode. All path pieces were
    validated against ``_FULL_NAME_RE`` so plain interpolation is safe.
    """
    stem = fname[: -len(".tar")]
    base = f"{_CORE_DUMPS_DIR}/{container}"
    tar_path = f"{base}/{fname}"
    workdir = f"{base}/.qactl-bt-{stem}"
    extract_cmd = (
        f"mkdir -p {workdir} && tar -xf {tar_path} -C {workdir} && "
        f"cat {workdir}/process.info.*"
    )
    core_path = f"{workdir}/{container}/{stem}.core"
    gdb_exs = "-ex bt -ex 'thread apply all bt'" if all_threads else "-ex bt"
    gdb_cmd = (
        f"lz4 -d -f {workdir}/{container}/{stem}.lz4 {core_path} && "
        f"gdb -batch -iex 'set debuginfod enabled off' {gdb_exs} "
        f"{binary} {core_path}"
    )
    assert_cmd = (
        f'for f in {workdir}/logs/*.stderr.log.gz; do '
        f'[ -f "$f" ] && zcat "$f"; done | grep -i assert | tail -n 5'
    )
    cleanup_cmd = f"rm -rf {workdir}"
    return workdir, extract_cmd, gdb_cmd, assert_cmd, cleanup_cmd


def _parse_backtrace(gdb_stdout: str) -> List[str]:
    """Extract the crashed thread's frame lines (``#N ...``) from gdb output.

    Only frames before the first ``Thread N`` header are taken, so with
    ``thread apply all bt`` the summary stays the crashed thread's stack
    (the full per-thread dump remains in ``stdout``).
    """
    frames: List[str] = []
    for line in (gdb_stdout or "").splitlines():
        if line.startswith("Thread ") and frames:
            break
        if re.match(r"^#\d+\s", line):
            frames.append(line.rstrip())
    return frames


@requires(CAP_SHELL)
def get_core_backtrace(
    full_name: str,
    all_threads: bool = False,
    keep: bool = False,
    confirm: bool = False,
    device: Optional[str] = None,
    host: Optional[str] = None,
    user: str = DEFAULT_USER,
    password: str = DEFAULT_PASSWORD,
    timeout: int = DEFAULT_CMD_TIMEOUT,
) -> Dict[str, Any]:
    """Extract the backtrace from a core-dump bundle (MUTATES device scratch).

    ``full_name`` is exactly as printed by ``list_cores`` — e.g.
    ``routing_engine/core-bgpd.cpid-199103.sig-6.2026-07-02.11-46-37.tar``.
    v1 supports **routing_engine bundles only**; other containers return
    an 'unsupported yet' error with the manual recipe pointer.

    The recipe (all inside ``run start shell`` on the active NCC, where
    the routing-engine binaries, gdb and lz4 live):

    1. ``tar -xf`` the bundle into a scratch workdir next to it
       (``.qactl-bt-<name>`` under ``/core/core_dumps/containers/...``).
    2. Read the crashed binary path from the bundle's ``process.info.*``
       (``fullpath=`` line) — NOT from the tar name, which may carry a
       thread name (``core-QuaggaLogger...`` is still bgpd).
    3. ``lz4 -d`` the core, then ``gdb -batch -ex bt`` against the binary
       (debuginfod force-disabled: the debuginfod host is unreachable from
       devices and would hang/spam otherwise). ``all_threads=True`` adds
       ``thread apply all bt``.
    4. Grep the bundled ``logs/*.stderr.log.gz`` for the assert line — it
       carries the exact ``file:line`` for the ticket.
    5. Remove the workdir (``keep=True`` leaves it for manual digging).

    Safety: writes only under its own scratch workdir, but it does write
    to the device — gated by ``confirm`` (CLI: ``--yes``). With
    ``confirm=False`` (default) nothing runs: the response is a dry-run
    listing the exact command lines that would execute.

    Args:
        full_name: ``<container>/<core-...>.tar`` as listed by ``list_cores``.
        all_threads: Also run ``thread apply all bt`` (full stdout carries it).
        keep: Keep the scratch workdir on the device after extraction.
        confirm: Execute for real. ``False`` = dry-run (no device traffic).
        device: Device alias (cl, sa, kira, slava-1, slava-2, ariel-cl).
        host: Raw hostname/IP (alternative to device).
        user: SSH username (default dnroot).
        password: SSH password (default dnroot).
        timeout: Per-step timeout seconds (the decompress+gdb step is
            floored at 180 s — big cores take a while).

    Response adds:
        - ``backtrace``: the crashed thread's frame lines (``#0`` ...).
        - ``signal`` / ``crashed_by``: from gdb's core header.
        - ``binary``: the crashed executable (from process.info).
        - ``assert_line`` / ``assert_lines``: from the bundled stderr log,
          when present.
        - ``workdir`` + ``kept``: when ``keep=True``.
        - ``stdout``: the raw gdb transcript (all threads included when
          ``all_threads=True``).
    """
    name = (full_name or "").strip()
    m = _FULL_NAME_RE.match(name)
    if not m:
        return error_response(
            f"full_name {name!r} does not look like a core bundle name; "
            "expected <container>/core-....tar exactly as printed by "
            "`qactl cli core list` (e.g. routing_engine/core-bgpd.cpid-"
            "199103.sig-6.2026-07-02.11-46-37.tar).",
            device=device, host=host, next_action=CORE_BT_NEXT_ACTION,
        )
    container, fname = m.group("container"), m.group("file")
    if container not in _SUPPORTED_CONTAINERS:
        return error_response(
            f"container {container!r} is not supported yet — core bundle "
            "layouts are not uniform across containers; v1 extracts "
            "routing_engine cores only.",
            device=device, host=host,
            next_action=CORE_BT_UNSUPPORTED_NEXT_ACTION,
        )

    workdir, extract_cmd, gdb_cmd, assert_cmd, cleanup_cmd = _bt_commands(
        container, fname, "<binary-from-process.info>", all_threads,
    )

    if not confirm:
        return make_response(
            device=device, host=host or "", command=extract_cmd,
            dry_run=True, core_tar=name, workdir=workdir,
            commands=[extract_cmd, gdb_cmd, assert_cmd]
            + ([] if keep else [cleanup_cmd]),
            warnings=[
                "Dry-run: confirm=False. Re-invoke with confirm=true "
                "(CLI: --yes) to execute.",
            ],
        )

    bt_timeout = max(timeout, _BT_MIN_TIMEOUT)
    executed: List[str] = []

    def _cleanup() -> None:
        if keep:
            return
        executed.append(cleanup_cmd)
        run_linux_on_device(
            "get_core_backtrace", device, host, user, password,
            cleanup_cmd, timeout, CORE_BT_NEXT_ACTION,
        )

    # 1. extract + read process.info (the authoritative binary path).
    executed.append(extract_cmd)
    r1 = run_linux_on_device(
        "get_core_backtrace", device, host, user, password,
        extract_cmd, bt_timeout, CORE_BT_NEXT_ACTION,
    )
    if r1.get("status") != "ok":
        r1.setdefault("commands", executed)
        return r1
    info = r1.get("stdout") or ""
    fp = _FULLPATH_RE.search(info)
    if not fp:
        _cleanup()
        return error_response(
            "could not read the crashed binary path (fullpath=) from the "
            f"bundle's process.info (got {info.strip()[:200]!r}); the tar "
            "may be missing or its layout may have shifted.",
            device=device, host=host, command=extract_cmd,
            next_action=CORE_BT_NEXT_ACTION,
        )
    binary = fp.group("path").replace("!", "/")

    # 2. decompress the core + gdb backtrace.
    _, _, gdb_cmd, _, _ = _bt_commands(container, fname, binary, all_threads)
    executed.append(gdb_cmd)
    r2 = run_linux_on_device(
        "get_core_backtrace", device, host, user, password,
        gdb_cmd, bt_timeout, CORE_BT_NEXT_ACTION,
    )
    if r2.get("status") != "ok":
        _cleanup()
        r2.setdefault("commands", executed)
        return r2
    gdb_out = r2.get("stdout") or ""
    frames = _parse_backtrace(gdb_out)

    # 3. best-effort: the assert line from the bundled stderr log.
    executed.append(assert_cmd)
    r3 = run_linux_on_device(
        "get_core_backtrace", device, host, user, password,
        assert_cmd, timeout, CORE_BT_NEXT_ACTION,
    )
    assert_lines = [
        ln.strip() for ln in (r3.get("stdout") or "").splitlines() if ln.strip()
    ] if r3.get("status") == "ok" else []

    _cleanup()

    response = make_response(
        device=r2.get("device"), host=r2.get("host") or "",
        command=gdb_cmd, stdout=gdb_out,
        core_tar=name, container=container, binary=binary,
        backtrace=frames, commands=executed,
    )
    sig = _SIGNAL_RE.search(gdb_out)
    if sig:
        response["signal"] = sig.group(1)
    gen = _GENERATED_BY_RE.search(gdb_out)
    if gen:
        response["crashed_by"] = gen.group(1)
    if assert_lines:
        response["assert_lines"] = assert_lines
        response["assert_line"] = assert_lines[-1]
    if keep:
        response["workdir"] = workdir
        response["kept"] = True
    if not frames:
        response["status"] = "error"
        response["errors"].append(
            "gdb produced no backtrace frames — see stdout for its output "
            "(wrong binary, truncated core, or gdb error)."
        )
        response["next_actions"].append(CORE_BT_NEXT_ACTION)
    return response


def register(mcp) -> None:
    """Wire this module's tools onto a FastMCP instance."""
    mcp.tool()(list_cores)
    mcp.tool()(get_core_backtrace)
