"""Backup file store on a remote SFTP host (``dnftp``).

Backups land on the same external SFTP server that ``ts_store`` uses for
tech-support tarballs — :data:`BACKUP_HOST`. Devices SFTP to ``dnftp`` with
the fixed account below into :data:`BACKUP_DIR` (the cli-mcp namespace
under ``/ftpdisk/dn/oshaboo/cli/backups``). The MCP, regardless of which
machine it runs on, verifies / lists / deletes those files by opening its
own SFTP session to the same host with the same credentials. Net effect:
the same code base works unchanged on any MCP host that can reach ``dnftp``
in the lab — backups don't depend on the local filesystem the way they
historically did.

Layout
------

The on-dnftp tree is **always rooted at the device alias**::

    <BACKUP_DIR>/<device>/                              # device root
    ├── <device>__<UTC>__<desc>.md                      # bucket=None
    └── <bucket>/                                       # optional sub-bucket
        └── <device>__<UTC>__<desc>.md

- ``device`` (mandatory) is the cli-mcp alias (``cl``, ``sa``, …) and
  is the **implicit top level** — every helper in this module derives
  the device folder from it; callers never pass the device as a
  bucket. This makes "show me everything for `cl`" a single
  ``listdir`` and gives each device a stable home for retention /
  pruning policies.
- ``bucket`` (optional, default ``None``) is a one-level sub-folder
  *under* the device root, used to group captures by purpose
  (``"nightly"`` for the scheduled job, ``"bug-1234-repro"`` for
  ad-hoc investigation captures, ``"save-for-later"``, …).
  ``bucket=None`` lands the file directly in the device root.

Bucket names are sanitised to ``[A-Za-z0-9._-]{1,60}``, may not
contain ``__`` (reserved as the filename separator), may not contain
``/`` (one level only — the device folder is the *first* level, the
bucket is the *second*), and must not match the canonical filename
shape (so a bucket can't be confused for a backup file).

Filename convention::

    <device>__<YYYYMMDD-HHMMSS>[__<desc>].md

- ``device`` prefix is **redundant with the folder** — but kept on
  purpose: ``restore_device`` uses the in-filename device prefix as a
  belt-and-suspenders safety check (refuses to apply ``cl__...md`` to
  ``device="sa"`` even if someone manually moved the file into
  ``BACKUP_DIR/sa/``).
- ``YYYYMMDD-HHMMSS`` is UTC, generated by the MCP at backup time.
- ``description`` is optional, sanitised to ``[A-Za-z0-9._-]{1,40}``.
  Missing description drops the trailing ``__<description>`` segment
  entirely.
- ``.md`` suffix is cosmetic — DNOS treats the filename as opaque, but the
  extension makes editors / IDEs render the saved config nicely.

DNOS ``save`` writes a plain text file with whatever name we hand it, and
``load override <name>`` accepts the same name verbatim, so the suffix
travels through both upload and restore unchanged.

Pre-2026-05-11 layout
---------------------

Earlier versions of this module used ``<BACKUP_DIR>/[<bucket>/]<file>``
where ``bucket`` defaulted to today's UTC date (``2026-05-10/`` etc.)
and the device alias appeared **only** in the filename. Existing files
in that shape are migrated to the new layout by
``scripts/scheduled/migrate-backups-layout.py``; nothing in this
module reads the old shape anymore.
"""

from __future__ import annotations

import posixpath
import re
import stat as _stat
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import List, Optional

import paramiko

from dnctl.cli.core.dnftp import (
    DNFTP_HOST,
    DNFTP_PASSWORD,
    DNFTP_USER,
    DNFTP_VRF,
    dnftp_sftp,
)


# --------------------------------------------------------------------------
# Backup-store layout. Host / credentials / VRF / SFTP context manager all
# come from dnctl.cli.core.dnftp — see that module for the deployment-pinned
# values. The ONLY backup-store-specific constant here is BACKUP_DIR; we
# re-export the dnftp values under the legacy ``BACKUP_*`` names so older
# call sites keep compiling, but new code should import from dnctl.cli.core.dnftp
# directly.
# --------------------------------------------------------------------------

BACKUP_DIR = "/ftpdisk/dn/oshaboo/cli/backups"

# Legacy aliases kept for backward compatibility with code that hasn't been
# migrated yet. New code: import from dnctl.cli.core.dnftp.
BACKUP_HOST = DNFTP_HOST
BACKUP_USER = DNFTP_USER
BACKUP_PASSWORD = DNFTP_PASSWORD
BACKUP_VRF = DNFTP_VRF


# --------------------------------------------------------------------------
# Filename grammar
# --------------------------------------------------------------------------

# Device aliases live in the canonical devices_mgmt0.json map and are
# alnum + ``._-``. We validate the filename against the same shape.
# Using non-greedy for device so the ``__`` separator splits cleanly
# even when the alias contains a single ``_`` (some lab chassis bake the
# SN into their System Name with single underscores, e.g.
# ``Slava_1_WK31C8V10001BP2``).
_FILENAME_RE = re.compile(
    r"^(?P<device>[A-Za-z0-9][A-Za-z0-9._-]*?)"
    r"__(?P<ts>\d{8}-\d{6})"
    r"(?:__(?P<description>[A-Za-z0-9][A-Za-z0-9._-]*))?"
    r"\.md$"
)

_DESCRIPTION_CLEAN_RE = re.compile(r"[^A-Za-z0-9._-]+")
_DESCRIPTION_MAX = 40

# Device-name and bucket-name shapes come from dnctl.core.validators —
# the same patterns are used by cert_store and any future cli-mcp tool
# that lands files on dnftp under a bucket. Local aliases keep the
# constants visible to existing call sites that read them.
from dnctl.core.validators import (
    BUCKET_NAME_MAX as _BUCKET_MAX,
    DEVICE_NAME_MAX as _DEVICE_MAX,
    validate_bucket_name as _validate_bucket_name,
    validate_device_name as _validate_device_name,
)


@dataclass(frozen=True)
class BackupFile:
    """Parsed view of one backup on ``dnftp``.

    ``path`` is the absolute POSIX path on :data:`BACKUP_HOST` (i.e. on
    dnftp, not on the MCP host) — there is no local copy. ``bucket`` is
    ``None`` for files in :data:`BACKUP_DIR` directly, or the sub-directory
    name for files in a sub-bucket.
    """

    filename: str
    device: str
    timestamp_utc: str              # "YYYY-MM-DDTHH:MM:SSZ"
    description: Optional[str]
    bucket: Optional[str]
    size_bytes: int
    path: str


def _utc_timestamp() -> str:
    """``YYYYMMDD-HHMMSS`` in UTC, used in backup filenames."""
    return datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")


def _sanitise_description(description: Optional[str]) -> Optional[str]:
    """Reduce description to the allowed charset, truncate, drop if empty."""
    if description is None:
        return None
    cleaned = _DESCRIPTION_CLEAN_RE.sub("_", description.strip()).strip("._-")
    if not cleaned:
        return None
    return cleaned[:_DESCRIPTION_MAX]


def validate_device(device: str) -> Optional[str]:
    """Return an error string if ``device`` is not a legal filename segment.

    Pass-through to :func:`dnctl.core.validators.validate_device_name`.
    """
    return _validate_device_name(device)


def validate_bucket(bucket: Optional[str]) -> Optional[str]:
    """Return an error string if ``bucket`` is not a legal sub-directory name.

    ``None`` is always valid (means "root"). The shared shape check
    (alnum + ``._-``, ≤60 chars, no ``__``, no ``/``) lives in
    :func:`dnctl.core.validators.validate_bucket_name`. The
    backup-store-specific extra constraint — the bucket must NOT also
    parse as a canonical backup filename, otherwise a file in the
    root could be confused with a sub-bucket — is enforced here.
    """
    err = _validate_bucket_name(bucket)
    if err:
        return err
    if bucket is not None and parse_filename(bucket) is not None:
        return (
            "bucket must not match the canonical backup filename shape "
            "(would be ambiguous with a file in the root bucket)."
        )
    return None


def make_filename(device: str, description: Optional[str] = None) -> str:
    """Build a canonical backup filename for ``device`` (description optional).

    Raises :class:`ValueError` if ``device`` is not a valid filename segment.
    ``description`` is quietly sanitised (illegal chars collapsed to ``_``;
    truncated to 40 chars; empty after sanitisation → dropped).
    """
    err = validate_device(device)
    if err:
        raise ValueError(err)
    ts = _utc_timestamp()
    clean_description = _sanitise_description(description)
    if clean_description:
        return f"{device}__{ts}__{clean_description}.md"
    return f"{device}__{ts}.md"


def parse_filename(filename: str) -> Optional[BackupFile]:
    """Parse a bare filename into :class:`BackupFile` without touching the network.

    Returns ``None`` if the name does not match the canonical shape. The
    returned :class:`BackupFile` has ``size_bytes=0``, ``bucket=None``,
    and an empty ``path`` — none of those are derivable from the bare
    filename alone (they all need the device folder + bucket the file
    actually lives in). Use :func:`stat_backup` for the populated form.
    """
    m = _FILENAME_RE.match(filename)
    if not m:
        return None
    ts_raw = m.group("ts")  # YYYYMMDD-HHMMSS
    iso = (
        f"{ts_raw[0:4]}-{ts_raw[4:6]}-{ts_raw[6:8]}T"
        f"{ts_raw[9:11]}:{ts_raw[11:13]}:{ts_raw[13:15]}Z"
    )
    return BackupFile(
        filename=filename,
        device=m.group("device"),
        timestamp_utc=iso,
        description=m.group("description"),
        bucket=None,
        size_bytes=0,
        path="",
    )


def _device_dir(device: str) -> str:
    """Absolute POSIX path of the per-device backup root on dnftp."""
    return posixpath.join(BACKUP_DIR, device)


def _bucket_dir(device: str, bucket: Optional[str]) -> str:
    """Absolute POSIX path of the directory holding backups for
    ``(device, bucket)``.

    ``bucket=None`` returns the device root; non-None returns the
    sub-bucket under it. The device dir is mandatory — there is no
    "loose under BACKUP_DIR" tier in this layout.
    """
    if bucket is None:
        return _device_dir(device)
    return posixpath.join(_device_dir(device), bucket)


def _file_path(filename: str, device: str, bucket: Optional[str]) -> str:
    """Absolute POSIX path of a backup file on dnftp."""
    return posixpath.join(_bucket_dir(device, bucket), filename)


def remote_path(
    filename: str, *, device: str, bucket: Optional[str] = None,
) -> str:
    """Public alias for the absolute on-dnftp path of a backup file.

    Pass to :func:`dnctl.cli.core.dnftp.build_upload_command` /
    :func:`dnctl.cli.core.dnftp.build_download_command` to render the DNOS
    ``request file upload|download ... protocol sftp vrf <vrf>``
    command line.
    """
    return _file_path(filename, device, bucket)


def _build_backupfile(
    filename: str,
    size_bytes: int,
    device: str,
    bucket: Optional[str],
) -> Optional[BackupFile]:
    parsed = parse_filename(filename)
    if parsed is None:
        return None
    return BackupFile(
        filename=parsed.filename,
        device=parsed.device,
        timestamp_utc=parsed.timestamp_utc,
        description=parsed.description,
        bucket=bucket,
        size_bytes=size_bytes,
        path=_file_path(filename, device, bucket),
    )


def _stat_in(
    sftp: paramiko.SFTPClient,
    filename: str,
    device: str,
    bucket: Optional[str],
) -> Optional[BackupFile]:
    """Stat ``filename`` in ``(device, bucket)`` using an open SFTP session."""
    parsed = parse_filename(filename)
    if parsed is None:
        return None
    path = _file_path(filename, device, bucket)
    try:
        attrs = sftp.stat(path)
    except FileNotFoundError:
        return None
    except IOError:
        return None
    return _build_backupfile(
        filename, int(attrs.st_size or 0), device, bucket,
    )


def stat_backup(
    filename: str, *, device: str, bucket: Optional[str] = None,
) -> Optional[BackupFile]:
    """Parse + remote-stat under ``(device, bucket)``.

    Returns ``None`` if the filename is malformed, ``device`` /
    ``bucket`` are invalid, or the file does not exist at the resolved
    path on :data:`BACKUP_HOST`.
    """
    if parse_filename(filename) is None:
        return None
    if validate_device(device) is not None:
        return None
    if validate_bucket(bucket) is not None:
        return None
    try:
        with dnftp_sftp() as sftp:
            return _stat_in(sftp, filename, device, bucket)
    except (paramiko.SSHException, OSError):
        return None


def _is_dir_attr(attrs: paramiko.SFTPAttributes) -> bool:
    return _stat.S_ISDIR(attrs.st_mode or 0)


def _is_reg_attr(attrs: paramiko.SFTPAttributes) -> bool:
    return _stat.S_ISREG(attrs.st_mode or 0)


def _list_one(
    sftp: paramiko.SFTPClient,
    device: str,
    bucket: Optional[str],
) -> List[BackupFile]:
    """List canonical backups inside ``BACKUP_DIR/<device>[/<bucket>]``.

    Filters the entries to only those whose in-filename device prefix
    matches ``device`` — guards against a stray ``cl__...md`` somehow
    sitting under ``BACKUP_DIR/sa/`` (manual mv, migration bug, etc.)
    showing up when the caller asked for ``sa``'s history.
    """
    out: List[BackupFile] = []
    bdir = _bucket_dir(device, bucket)
    try:
        entries = sftp.listdir_attr(bdir)
    except FileNotFoundError:
        return out
    except IOError:
        return out
    for entry in entries:
        if not _is_reg_attr(entry):
            continue
        backup = _build_backupfile(
            entry.filename, int(entry.st_size or 0), device, bucket,
        )
        if backup is None:
            continue
        if backup.device != device:
            continue
        out.append(backup)
    return out


def _list_device_buckets(
    sftp: paramiko.SFTPClient, device: str,
) -> List[str]:
    """Sub-bucket dir names under ``BACKUP_DIR/<device>/``, validator-filtered."""
    out: List[str] = []
    try:
        entries = sftp.listdir_attr(_device_dir(device))
    except (FileNotFoundError, IOError):
        return out
    for entry in entries:
        if not _is_dir_attr(entry):
            continue
        if validate_bucket(entry.filename) is not None:
            continue
        out.append(entry.filename)
    out.sort()
    return out


def _list_devices(sftp: paramiko.SFTPClient) -> List[str]:
    """Top-level device dir names under ``BACKUP_DIR/``, validator-filtered."""
    out: List[str] = []
    try:
        entries = sftp.listdir_attr(BACKUP_DIR)
    except (FileNotFoundError, IOError):
        return out
    for entry in entries:
        if not _is_dir_attr(entry):
            continue
        if validate_device(entry.filename) is not None:
            continue
        out.append(entry.filename)
    out.sort()
    return out


def list_backups(
    device: Optional[str] = None,
    limit: Optional[int] = 100,
    bucket: Optional[str] = None,
) -> List[BackupFile]:
    """List backups under :data:`BACKUP_DIR` on :data:`BACKUP_HOST`, newest first.

    Walking strategy:

    - ``device="<d>"``, ``bucket=None``: list ``BACKUP_DIR/<d>/`` AND
      every sub-bucket under it.
    - ``device="<d>"``, ``bucket="<b>"``: list ONLY
      ``BACKUP_DIR/<d>/<b>/``. Returns an empty list if it doesn't
      exist.
    - ``device=None``, ``bucket=None``: walk every device dir under
      ``BACKUP_DIR`` AND every sub-bucket under each device. Heavy —
      pass a ``device`` if you can.
    - ``device=None``, ``bucket="<b>"``: walk every device, but only
      look at the ``<b>`` sub-bucket under each. Useful for "show me
      every fleet member's `nightly`".

    Files that don't match the canonical name are silently skipped —
    callers that want to surface them should use :func:`list_orphans`.
    Each returned :class:`BackupFile` has a populated ``path`` and
    ``bucket`` (``None`` if the file was in the device root).
    """
    if device is not None and validate_device(device) is not None:
        return []
    if bucket is not None and validate_bucket(bucket) is not None:
        return []

    out: List[BackupFile] = []
    with dnftp_sftp() as sftp:
        target_devices: List[str] = (
            [device] if device is not None else _list_devices(sftp)
        )
        for d in target_devices:
            if bucket is not None:
                out.extend(_list_one(sftp, d, bucket))
            else:
                out.extend(_list_one(sftp, d, None))
                for b in _list_device_buckets(sftp, d):
                    out.extend(_list_one(sftp, d, b))
    # Newest first — the timestamp segment is lex-sortable because of
    # the YYYYMMDD-HHMMSS shape. Tie-break on (device, bucket) so the
    # order is stable across calls.
    out.sort(
        key=lambda b: (b.filename, b.device, b.bucket or ""),
        reverse=True,
    )
    if limit is not None and limit > 0:
        out = out[:limit]
    return out


def list_buckets(device: Optional[str] = None) -> List[str]:
    """Return bucket directory names under ``BACKUP_DIR``.

    - ``device="<d>"``: sub-bucket names under ``BACKUP_DIR/<d>/``,
      sorted (e.g. ``["bug-1234", "nightly"]``).
    - ``device=None``: top-level device-folder names under
      ``BACKUP_DIR/``, sorted (e.g. ``["cl", "kira", "sa"]``).

    Excludes any entry that isn't a directory or whose name fails the
    relevant validator.
    """
    if device is not None and validate_device(device) is not None:
        return []
    with dnftp_sftp() as sftp:
        if device is None:
            return _list_devices(sftp)
        return _list_device_buckets(sftp, device)


def list_orphans() -> List[str]:
    """Files under :data:`BACKUP_DIR` whose names or locations don't fit.

    Walks the full per-device tree and surfaces:

    - Top-level entries under ``BACKUP_DIR/`` that aren't a valid
      device dir (rendered as ``"<name>/"`` for dirs,
      ``"<name>"`` for files — both indicate a layout drift).
    - Files directly under any device dir whose names don't parse.
    - Files inside a sub-bucket whose names don't parse.
    - Sub-bucket entries (under a device dir) that don't parse as a
      valid bucket name (rendered as ``"<device>/<name>/"``).

    Used by ``list_backups`` to warn agents about a dnftp tree that
    has drifted from the canonical layout.
    """
    out: List[str] = []
    with dnftp_sftp() as sftp:
        try:
            top_entries = sftp.listdir_attr(BACKUP_DIR)
        except (FileNotFoundError, IOError):
            return out
        device_dirs: List[str] = []
        for entry in top_entries:
            if _is_dir_attr(entry):
                if validate_device(entry.filename) is None:
                    device_dirs.append(entry.filename)
                else:
                    out.append(entry.filename + "/")
                continue
            if _is_reg_attr(entry):
                out.append(entry.filename)
        for device in device_dirs:
            try:
                ddir_entries = sftp.listdir_attr(_device_dir(device))
            except (FileNotFoundError, IOError):
                continue
            sub_buckets: List[str] = []
            for entry in ddir_entries:
                if _is_dir_attr(entry):
                    if validate_bucket(entry.filename) is None:
                        sub_buckets.append(entry.filename)
                    else:
                        out.append(f"{device}/{entry.filename}/")
                    continue
                if not _is_reg_attr(entry):
                    continue
                if parse_filename(entry.filename) is None:
                    out.append(f"{device}/{entry.filename}")
            for bucket in sub_buckets:
                try:
                    sub_entries = sftp.listdir_attr(
                        _bucket_dir(device, bucket)
                    )
                except (FileNotFoundError, IOError):
                    continue
                for entry in sub_entries:
                    if not _is_reg_attr(entry):
                        continue
                    if parse_filename(entry.filename) is None:
                        out.append(f"{device}/{bucket}/{entry.filename}")
    out.sort()
    return out


# Anything at or below this path is fair game for ``ensure_dir`` to create
# on demand. Parents up to and including this prefix are presumed to exist
# already on dnftp (owned by ``dn`` so the SFTP user can mkdir under it).
# Bumping this requires either a manual ``ssh dnftp mkdir`` on the new
# parent or relaxing the prefix here.
_BACKUP_MKDIR_ROOT = "/ftpdisk/dn/oshaboo"


def ensure_dir(
    *, device: str, bucket: Optional[str] = None,
) -> None:
    """Make sure ``BACKUP_DIR/<device>[/<bucket>]`` exists on dnftp.

    Devices SFTP into this directory directly — sshd will not create
    parents on demand, so a missing dir manifests as a confusing
    ``Failure`` from DNOS. Call this right before kicking off an
    upload so the very first ``backup_device`` for a new device just
    works. Idempotent; safe to call repeatedly. Creates every directory
    between :data:`_BACKUP_MKDIR_ROOT` (presumed to exist already on
    dnftp) and the requested leaf — typically just ``cli/``,
    ``backups/``, ``<device>/``, and the optional ``<bucket>/``.
    """
    err = validate_device(device)
    if err:
        raise ValueError(err)
    if bucket is not None:
        b_err = validate_bucket(bucket)
        if b_err:
            raise ValueError(b_err)
    leaf = _bucket_dir(device, bucket)
    with dnftp_sftp() as sftp:
        _mkdir_p(sftp, leaf)


def _mkdir_p(sftp: paramiko.SFTPClient, path: str) -> None:
    """Idempotent ``mkdir -p`` between :data:`_BACKUP_MKDIR_ROOT` and ``path``.

    Refuses to create anything outside the mkdir root — a thin safety net
    against a malformed :data:`BACKUP_DIR` constant or a path-traversing
    bucket name that slipped past validation.
    """
    norm = posixpath.normpath(path)
    root = posixpath.normpath(_BACKUP_MKDIR_ROOT)
    if norm != root and not norm.startswith(root + "/"):
        raise ValueError(
            f"refusing to mkdir {path!r}: outside backup mkdir root "
            f"{_BACKUP_MKDIR_ROOT!r}."
        )
    # Build the ancestor chain root -> norm.
    rel = norm[len(root):].lstrip("/")
    parts = [p for p in rel.split("/") if p] if rel else []
    cur = root
    chain = [cur]
    for p in parts:
        cur = posixpath.join(cur, p)
        chain.append(cur)
    for entry in chain:
        _mkdir_idempotent(sftp, entry)


def _mkdir_idempotent(sftp: paramiko.SFTPClient, path: str) -> None:
    try:
        sftp.stat(path)
        return
    except FileNotFoundError:
        pass
    except IOError:
        pass
    try:
        sftp.mkdir(path)
    except (IOError, OSError):
        # Race: another caller may have just created it. Re-stat to
        # confirm; if still missing, propagate.
        sftp.stat(path)


def remote_url(
    filename: str, *, device: str, bucket: Optional[str] = None,
) -> str:
    """Build the ``user@host:/abs/path`` URL DNOS uses in ``request file ...``.

    Uses single-colon scp-style form matching the tech-support uploads;
    DNOS accepts both this and the ``://`` form but this one is less
    ambiguous.
    """
    return (
        f"{BACKUP_USER}@{BACKUP_HOST}:"
        f"{_file_path(filename, device, bucket)}"
    )


def download_bytes(
    filename: str, *, device: str, bucket: Optional[str] = None,
) -> bytes:
    """SFTP-fetch ``filename`` under ``(device, bucket)`` and return bytes."""
    if parse_filename(filename) is None:
        raise ValueError(
            f"refusing to download {filename!r}: not a canonical backup name."
        )
    d_err = validate_device(device)
    if d_err:
        raise ValueError(f"refusing to download with invalid device: {d_err}")
    b_err = validate_bucket(bucket)
    if b_err:
        raise ValueError(f"refusing to download with invalid bucket: {b_err}")
    src = _file_path(filename, device, bucket)
    with dnftp_sftp() as sftp:
        with sftp.open(src, "rb") as fh:
            return fh.read()


def delete_backup(
    filename: str, *, device: str, bucket: Optional[str] = None,
) -> bool:
    """Delete a backup under ``(device, bucket)``. ``True`` if deleted,
    ``False`` if missing.

    Refuses to touch anything whose name doesn't parse, and rejects
    invalid device / bucket — a thin safety net against a caller
    smuggling a path traversal through any of the three.
    """
    if parse_filename(filename) is None:
        raise ValueError(
            f"refusing to delete {filename!r}: not a canonical backup name."
        )
    d_err = validate_device(device)
    if d_err:
        raise ValueError(f"refusing to delete with invalid device: {d_err}")
    b_err = validate_bucket(bucket)
    if b_err:
        raise ValueError(f"refusing to delete with invalid bucket: {b_err}")
    path = _file_path(filename, device, bucket)
    with dnftp_sftp() as sftp:
        try:
            sftp.remove(path)
            return True
        except FileNotFoundError:
            return False
        except IOError:
            return False


__all__ = [
    "BACKUP_HOST",
    "BACKUP_USER",
    "BACKUP_PASSWORD",
    "BACKUP_DIR",
    "BACKUP_VRF",
    "BackupFile",
    "validate_device",
    "validate_bucket",
    "make_filename",
    "parse_filename",
    "stat_backup",
    "list_backups",
    "list_buckets",
    "list_orphans",
    "ensure_dir",
    "remote_path",
    "remote_url",
    "download_bytes",
    "delete_backup",
]
