"""Tech-support tarball store on a remote SFTP host (``dnftp``).

Unlike :mod:`backup_store` — which lands files on the same OS that runs the
MCP and verifies via local filesystem — tech-support tarballs land on a
separate SFTP server (:data:`TS_HOST`). Devices SFTP to ``dnftp`` with the
fixed account below into :data:`TS_DIR`. The MCP, running on ``oshaboo-dev``,
verifies / lists / deletes those files by opening its own SFTP session to
the same host with the same credentials — so all bookkeeping still happens
on the local machine, just over the network instead of via local FS.

Filename convention on ``dnftp``::

    <device>__<YYYYMMDD-HHMMSS>__<name>.tar

- ``device`` is the alias (``cl``, ``sa``, ...), pinned by the tool. Same
  safety rationale as backups: device prefix can't be forged by the caller.
- ``YYYYMMDD-HHMMSS`` is UTC, generated by the MCP at upload time.
- ``name`` is the user-supplied tech-support name (same value passed to
  ``request system tech-support <name>`` on the device), sanitised to
  ``[A-Za-z0-9._-]{1,40}``. It is required — unlike backup descriptions — so
  the MCP can reconcile the DNOS-generated source filename
  (``ts_<name>_<HH_MM_SS>_<DD-MM-YYYY>.tar``) against what we kicked off.

The on-device source file in ``/techsupport/`` is left in place after upload
(same policy as ``backup_device``).
"""

from __future__ import annotations

import posixpath
import re
import stat as _stat
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import List, Optional

import paramiko

from dnctl.cli.core.dnftp import (
    DNFTP_HOST,
    DNFTP_PASSWORD,
    DNFTP_USER,
    DNFTP_VRF,
    dnftp_sftp,
)


# --------------------------------------------------------------------------
# Tech-support storage layout. Host / credentials / VRF / SFTP context
# manager all come from dnctl.cli.core.dnftp — see that module for the
# deployment-pinned values. The ONLY ts-specific constant here is TS_DIR;
# the legacy ``TS_*`` host/user/password/vrf names re-export the dnftp
# values so older call sites keep compiling.
# --------------------------------------------------------------------------

TS_DIR = "/ftpdisk/dn/oshaboo/ts"

# Legacy aliases kept for backward compatibility with code that hasn't been
# migrated yet. New code: import from dnctl.cli.core.dnftp.
TS_HOST = DNFTP_HOST
TS_USER = DNFTP_USER
TS_PASSWORD = DNFTP_PASSWORD
TS_VRF = DNFTP_VRF


# --------------------------------------------------------------------------
# Filename grammar
# --------------------------------------------------------------------------

_FILENAME_RE = re.compile(
    r"^(?P<device>[A-Za-z0-9][A-Za-z0-9._-]*?)"
    r"__(?P<ts>\d{8}-\d{6})"
    r"__(?P<name>[A-Za-z0-9][A-Za-z0-9._-]*)\.tar$"
)

_NAME_CLEAN_RE = re.compile(r"[^A-Za-z0-9._-]+")
_NAME_MAX = 40
_DEVICE_MAX = 40


@dataclass(frozen=True)
class TSFile:
    """Parsed view of one tech-support tarball on ``dnftp``.

    ``path`` is the absolute POSIX path on :data:`TS_HOST` (i.e. on dnftp,
    not on the MCP host) — there is no local copy.
    """

    filename: str
    device: str
    timestamp_utc: str              # "YYYY-MM-DDTHH:MM:SSZ"
    name: str
    size_bytes: int
    path: str


def _utc_timestamp() -> str:
    """``YYYYMMDD-HHMMSS`` in UTC, used in tech-support filenames."""
    return datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")


def validate_device(device: str) -> Optional[str]:
    """Return an error string if ``device`` is not a legal filename segment."""
    if not isinstance(device, str) or not device:
        return "device must be a non-empty string."
    if len(device) > _DEVICE_MAX:
        return f"device name too long (> {_DEVICE_MAX} chars)."
    if not re.match(r"^[A-Za-z0-9][A-Za-z0-9._-]*$", device):
        return (
            "device name must start with alnum and contain only "
            "[A-Za-z0-9._-] (no underscores allowed besides the built-in "
            "field separator)."
        )
    if "__" in device:
        return "device name must not contain '__' (reserved as field separator)."
    return None


def sanitise_name(name: Optional[str]) -> Optional[str]:
    """Reduce ``name`` to the allowed charset, truncate, return ``None`` if empty.

    Illegal characters collapse to ``_``; leading/trailing ``._-`` are stripped;
    result is truncated to 40 chars. Returns ``None`` for ``None`` / empty /
    all-illegal input.
    """
    if name is None:
        return None
    cleaned = _NAME_CLEAN_RE.sub("_", name.strip()).strip("._-")
    if not cleaned:
        return None
    return cleaned[:_NAME_MAX]


def validate_name(name: str) -> Optional[str]:
    """Return an error string if ``name`` is missing / empty after sanitise."""
    if not isinstance(name, str):
        return "name must be a non-empty string."
    cleaned = sanitise_name(name)
    if not cleaned:
        return (
            "name must contain at least one [A-Za-z0-9._-] character "
            "after sanitisation."
        )
    return None


def make_filename(device: str, name: str) -> str:
    """Build a canonical tech-support filename for ``(device, name)``.

    Raises :class:`ValueError` if ``device`` or ``name`` is invalid. ``name``
    is quietly sanitised (illegal chars → ``_``; truncated to 40 chars).
    """
    err = validate_device(device)
    if err:
        raise ValueError(err)
    clean = sanitise_name(name)
    if not clean:
        raise ValueError(
            "name must contain at least one [A-Za-z0-9._-] character "
            "after sanitisation."
        )
    ts = _utc_timestamp()
    return f"{device}__{ts}__{clean}.tar"


def parse_filename(filename: str) -> Optional[TSFile]:
    """Parse a bare filename into :class:`TSFile` without touching the network.

    Returns ``None`` if the name does not match the canonical shape. The
    ``size_bytes`` field comes out as ``0``; use :func:`stat_ts` for the
    real size.
    """
    m = _FILENAME_RE.match(filename)
    if not m:
        return None
    ts_raw = m.group("ts")  # YYYYMMDD-HHMMSS
    iso = (
        f"{ts_raw[0:4]}-{ts_raw[4:6]}-{ts_raw[6:8]}T"
        f"{ts_raw[9:11]}:{ts_raw[11:13]}:{ts_raw[13:15]}Z"
    )
    return TSFile(
        filename=filename,
        device=m.group("device"),
        timestamp_utc=iso,
        name=m.group("name"),
        size_bytes=0,
        path=posixpath.join(TS_DIR, filename),
    )


def _build_tsfile(filename: str, size_bytes: int) -> Optional[TSFile]:
    parsed = parse_filename(filename)
    if parsed is None:
        return None
    return TSFile(
        filename=parsed.filename,
        device=parsed.device,
        timestamp_utc=parsed.timestamp_utc,
        name=parsed.name,
        size_bytes=size_bytes,
        path=parsed.path,
    )


def stat_ts(filename: str) -> Optional[TSFile]:
    """Parse + remote-stat. Returns ``None`` if the name is malformed or the
    file does not exist on :data:`TS_HOST`."""
    parsed = parse_filename(filename)
    if parsed is None:
        return None
    try:
        with dnftp_sftp() as sftp:
            try:
                attrs = sftp.stat(parsed.path)
            except FileNotFoundError:
                return None
            except IOError:
                # paramiko raises IOError("No such file") on older versions.
                return None
    except (paramiko.SSHException, OSError):
        return None
    size = int(attrs.st_size or 0)
    return _build_tsfile(parsed.filename, size)


def list_ts(device: Optional[str] = None, limit: Optional[int] = 100) -> List[TSFile]:
    """List tech-support files in :data:`TS_DIR` on :data:`TS_HOST`, newest first.

    Files that don't match the canonical name are silently skipped — callers
    that want to surface orphans should use :func:`list_orphans`.
    """
    out: List[TSFile] = []
    with dnftp_sftp() as sftp:
        for entry in sftp.listdir_attr(TS_DIR):
            mode = entry.st_mode or 0
            if not _stat.S_ISREG(mode):
                continue
            tsfile = _build_tsfile(entry.filename, int(entry.st_size or 0))
            if tsfile is None:
                continue
            if device is not None and tsfile.device != device:
                continue
            out.append(tsfile)
    out.sort(key=lambda t: t.filename, reverse=True)
    if limit is not None and limit > 0:
        out = out[:limit]
    return out


def list_orphans() -> List[str]:
    """Filenames under :data:`TS_DIR` (on dnftp) that don't match the canonical shape."""
    out: List[str] = []
    with dnftp_sftp() as sftp:
        for entry in sftp.listdir_attr(TS_DIR):
            mode = entry.st_mode or 0
            if not _stat.S_ISREG(mode):
                continue
            if parse_filename(entry.filename) is None:
                out.append(entry.filename)
    out.sort()
    return out


def remote_url(filename: str) -> str:
    """Build the ``user@host:/abs/path`` URL DNOS uses in ``request file ...``.

    Uses single-colon scp-style form matching the backup uploads; DNOS
    accepts both this and the ``://`` form but this one is less ambiguous.
    """
    return f"{TS_USER}@{TS_HOST}:{TS_DIR}/{filename}"


def remote_path(filename: str) -> str:
    """Absolute on-dnftp POSIX path of a tech-support file.

    Pass to :func:`dnctl.cli.core.dnftp.build_upload_command` /
    :func:`dnctl.cli.core.dnftp.build_download_command` to render the DNOS
    ``request file upload|download ... protocol sftp vrf <vrf>`` command
    line.
    """
    return posixpath.join(TS_DIR, filename)


def delete_ts(filename: str) -> bool:
    """Delete a tech-support file on :data:`TS_HOST`. Returns True if deleted,
    False if missing.

    Refuses to touch anything whose name doesn't parse — a thin safety net
    against a caller smuggling a path traversal through the ``filename`` arg.
    """
    if parse_filename(filename) is None:
        raise ValueError(
            f"refusing to delete {filename!r}: not a canonical tech-support name."
        )
    path = posixpath.join(TS_DIR, filename)
    with dnftp_sftp() as sftp:
        try:
            sftp.remove(path)
            return True
        except FileNotFoundError:
            return False
        except IOError:
            return False


__all__ = [
    "TS_HOST",
    "TS_USER",
    "TS_PASSWORD",
    "TS_DIR",
    "TS_VRF",
    "TSFile",
    "validate_device",
    "validate_name",
    "sanitise_name",
    "make_filename",
    "parse_filename",
    "stat_ts",
    "list_ts",
    "list_orphans",
    "remote_url",
    "delete_ts",
]
